package com.sanjose.inventory.service;

import com.sanjose.inventory.dto.ScannerPayload;
import com.sanjose.inventory.dto.ScannerResponse;
import com.sanjose.inventory.entity.EquipmentRecord;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Optional;

/**
 * MOCK HANDSHAKE — Hardware QR/Barcode Scanner Integration
 *
 * This service represents the Business Tier handler for a physical scanner device.
 * In production, the scanner would POST to /api/scanner/receive over a local
 * network or USB-to-serial bridge. For demonstration, the payload is simulated
 * by the frontend or Postman, proving architectural readiness.
 *
 * Architecture path:
 *   Hardware Device → POST /api/scanner/receive
 *       → MockScannerIntegrationService (Business Tier — this file)
 *           → EquipmentRecordService (Data Tier via stored procedures)
 *               → ScannerResponse → UI (Presentation Tier)
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class MockScannerIntegrationService {

    private static final String QR_PREFIX = "ict-inv:";

    private final EquipmentRecordService equipmentService;
    private final AuditLogService auditLogService;

    public ScannerResponse processScan(ScannerPayload payload) {

        // ── Step 1: Gatekeeper Validation ────────────────────────────────────
        if (payload == null || payload.rawCode() == null || payload.rawCode().isBlank()) {
            log.warn("[MockScanner] Received empty payload from device: {}", payload);
            return new ScannerResponse("INVALID", "Scan payload is empty or malformed.", null);
        }

        if (payload.deviceId() == null || payload.deviceId().isBlank()) {
            log.warn("[MockScanner] No device ID provided in payload.");
            return new ScannerResponse("INVALID", "Scanner device ID is missing.", null);
        }

        log.info("[MockScanner] Received scan from device '{}' | mode: {} | code: {}",
                payload.deviceId(), payload.scannerMode(), payload.rawCode());

        // ── Step 2: Simulate hardware connection verified ─────────────────────
        String connectionStatus = simulateHardwareHandshake(payload.deviceId());
        if (!"CONNECTION_VERIFIED".equals(connectionStatus)) {
            return new ScannerResponse("ERROR", "Hardware handshake failed: " + connectionStatus, null);
        }

        // ── Step 3: Resolve the scanned code to an equipment record ───────────
        String code = payload.rawCode().trim();

        Optional<EquipmentRecord> match = Optional.empty();

        // QR code format: "ict-inv:{id}"
        if (code.startsWith(QR_PREFIX)) {
            String idStr = code.substring(QR_PREFIX.length());
            try {
                Long id = Long.parseLong(idStr);
                match = Optional.of(equipmentService.findById(id));
            } catch (NumberFormatException | com.sanjose.inventory.exception.ResourceNotFoundException e) {
                log.warn("[MockScanner] Could not resolve QR code ID: {}", idStr);
            }
        }

        // Fallback: search by item code
        if (match.isEmpty()) {
            match = equipmentService.findAll().stream()
                    .filter(e -> code.equalsIgnoreCase(e.getItemCode()))
                    .findFirst();
        }

        // ── Step 4: Feedback Loop — return result to Presentation Tier ────────
        if (match.isPresent()) {
            EquipmentRecord equipment = match.get();
            auditLogService.log("CREATE", "TRACKING",
                    "Hardware scanner '" + payload.deviceId() + "' scanned equipment ID " + equipment.getId());

            log.info("[MockScanner] Match found: equipment ID {}", equipment.getId());
            return new ScannerResponse("OK",
                    "Equipment identified successfully via " + payload.scannerMode() + " scanner.",
                    equipment);
        }

        log.warn("[MockScanner] No equipment matched code: {}", code);
        return new ScannerResponse("NOT_FOUND",
                "No equipment matched the scanned code. Ensure QR was generated by this system.",
                null);
    }

    private String simulateHardwareHandshake(String deviceId) {
        if (deviceId != null && !deviceId.isBlank()) {
            log.info("[MockScanner] Handshake OK — device '{}' is online.", deviceId);
            return "CONNECTION_VERIFIED";
        }
        return "DEVICE_OFFLINE";
    }
}
